server:
  port: 6666

spring:
  datasource:
    url: jdbc:mysql://148.70.208.105:3306/city-governance?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: jiading
    password: Wiseljz131231
